2014/04/22 02:48:31 [error] [php] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (/var/www/workspace_php/pythonfornoobs/protected/views/layouts/main.php:51)
Stack trace:
#0 /var/www/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#1 /var/www/yii/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#2 /var/www/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#3 /var/www/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#4 /var/www/yii/framework/web/CBaseController.php(206): CContentDecorator->run()
#5 /var/www/yii/framework/web/CBaseController.php(300): SiteController->endWidget()
#6 /var/www/workspace_php/pythonfornoobs/protected/views/layouts/column1.php(6): SiteController->endContent()
#7 /var/www/yii/framework/web/CBaseController.php(126): require()
#8 /var/www/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#9 /var/www/yii/framework/web/CController.php(784): SiteController->renderFile()
#10 /var/www/workspace_php/pythonfornoobs/protected/controllers/SiteController.php(32): SiteController->render()
#11 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#12 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#13 /var/www/yii/framework/web/CController.php(286): SiteController->runAction()
#14 /var/www/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#15 /var/www/yii/framework/web/CWebApplication.php(282): SiteController->run()
#16 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#17 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#18 /var/www/workspace_php/pythonfornoobs/index.php(13): CWebApplication->run()
REQUEST_URI=/workspace_php/pythonfornoobs/
in /var/www/workspace_php/pythonfornoobs/protected/views/layouts/main.php (51)
in /var/www/workspace_php/pythonfornoobs/protected/views/layouts/column1.php (6)
in /var/www/workspace_php/pythonfornoobs/protected/controllers/SiteController.php (32)
2014/04/22 00:54:57 [error] [php] Object of class CTheme could not be converted to string (/var/www/workspace_php/pythonfornoobs/themes/bootstrap/views/layouts/main.php:8)
Stack trace:
#0 /var/www/yii/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#1 /var/www/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#2 /var/www/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#3 /var/www/yii/framework/web/CBaseController.php(206): CContentDecorator->run()
#4 /var/www/yii/framework/web/CBaseController.php(300): SiteController->endWidget()
#5 /var/www/workspace_php/pythonfornoobs/protected/views/layouts/column1.php(6): SiteController->endContent()
#6 /var/www/yii/framework/web/CBaseController.php(126): require()
#7 /var/www/yii/framework/web/CBaseController.php(95): SiteController->renderInternal()
#8 /var/www/yii/framework/web/CController.php(784): SiteController->renderFile()
#9 /var/www/workspace_php/pythonfornoobs/protected/controllers/SiteController.php(32): SiteController->render()
#10 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#11 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#12 /var/www/yii/framework/web/CController.php(286): SiteController->runAction()
#13 /var/www/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#14 /var/www/yii/framework/web/CWebApplication.php(282): SiteController->run()
#15 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#16 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#17 /var/www/workspace_php/pythonfornoobs/index.php(15): CWebApplication->run()
REQUEST_URI=/workspace_php/pythonfornoobs/index.php
in /var/www/workspace_php/pythonfornoobs/themes/bootstrap/views/layouts/main.php (8)
in /var/www/workspace_php/pythonfornoobs/protected/views/layouts/column1.php (6)
in /var/www/workspace_php/pythonfornoobs/protected/controllers/SiteController.php (32)
2014/04/22 00:55:31 [error] [exception.CException] exception 'CException' with message 'A propriedade "CTheme.bootstrap" não está definida.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/workspace_php/pythonfornoobs/themes/bootstrap/views/layouts/main.php(8): CComponent->__get('bootstrap')
#1 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/worksp...')
#2 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/worksp...', Array, true)
#3 /var/www/yii/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/var/www/worksp...', Array, true)
#4 /var/www/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#5 /var/www/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#6 /var/www/yii/framework/web/CBaseController.php(206): COutputProcessor->run()
#7 /var/www/yii/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#8 /var/www/workspace_php/pythonfornoobs/protected/views/layouts/column1.php(6): CBaseController->endContent()
#9 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/worksp...')
#10 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/worksp...', Array, true)
#11 /var/www/yii/framework/web/CController.php(784): CBaseController->renderFile('/var/www/worksp...', Array, true)
#12 /var/www/workspace_php/pythonfornoobs/protected/controllers/SiteController.php(32): CController->render('index')
#13 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#14 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#15 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#16 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('')
#18 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#19 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#20 /var/www/workspace_php/pythonfornoobs/index.php(15): CApplication->run()
#21 {main}
REQUEST_URI=/workspace_php/pythonfornoobs/index.php
HTTP_REFERER=http://127.0.0.1/workspace_php/pythonfornoobs/index.php
---
2014/04/22 02:00:29 [error] [exception.CException] exception 'CException' with message 'A propriedade "UserIdentity._id" não está definida.' in /var/www/yii/framework/base/CComponent.php:173
Stack trace:
#0 /var/www/workspace_php/pythonfornoobs/protected/components/UserIdentity.php(37): CComponent->__set('_id', '1')
#1 /var/www/workspace_php/pythonfornoobs/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /var/www/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /var/www/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /var/www/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /var/www/workspace_php/pythonfornoobs/protected/controllers/SiteController.php(94): CModel->validate()
#6 /var/www/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /var/www/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /var/www/workspace_php/pythonfornoobs/index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/workspace_php/pythonfornoobs/index.php/site/login
HTTP_REFERER=http://127.0.0.1/workspace_php/pythonfornoobs/index.php/site/login
---
2014/04/22 02:14:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "us".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('us')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/workspace_php/pythonfornoobs/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/workspace_php/pythonfornoobs/index.php/us
---
2014/04/22 02:29:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Você não está autorizado a realizar essa operação.' in /var/www/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /var/www/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Voc?? n??o est?...')
#1 /var/www/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /var/www/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /var/www/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /var/www/workspace_php/pythonfornoobs/index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/workspace_php/pythonfornoobs/index.php/user/admin
HTTP_REFERER=http://127.0.0.1/workspace_php/pythonfornoobs/index.php/user/index
---
2014/04/22 02:42:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "create".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('create')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/workspace_php/pythonfornoobs/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/workspace_php/pythonfornoobs/index.php/create
---
2014/04/22 03:04:03 [error] [exception.CException] exception 'CException' with message 'A propriedade "User.birth_date" não está definida.' in /var/www/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('birth_date')
#1 /var/www/workspace_php/pythonfornoobs/protected/views/user/_view.php(28): CActiveRecord->__get('birth_date')
#2 /var/www/yii/framework/web/CBaseController.php(130): require('/var/www/worksp...')
#3 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/worksp...', Array, false)
#4 /var/www/yii/framework/zii/widgets/CListView.php(291): CBaseController->renderFile('/var/www/worksp...', Array)
#5 /var/www/yii/framework/zii/widgets/CBaseListView.php(167): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 /var/www/yii/framework/zii/widgets/CBaseListView.php(150): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{sort...')
#8 /var/www/yii/framework/zii/widgets/CBaseListView.php(135): CBaseListView->renderContent()
#9 /var/www/yii/framework/web/CBaseController.php(173): CBaseListView->run()
#10 /var/www/workspace_php/pythonfornoobs/protected/views/user/index.php(13): CBaseController->widget('zii.widgets.CLi...', Array)
#11 /var/www/yii/framework/web/CBaseController.php(126): require('/var/www/worksp...')
#12 /var/www/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/worksp...', Array, true)
#13 /var/www/yii/framework/web/CController.php(869): CBaseController->renderFile('/var/www/worksp...', Array, true)
#14 /var/www/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#15 /var/www/workspace_php/pythonfornoobs/protected/controllers/UserController.php(128): CController->render('index', Array)
#16 /var/www/yii/framework/web/actions/CInlineAction.php(49): UserController->actionIndex()
#17 /var/www/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#18 /var/www/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 /var/www/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#20 /var/www/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 /var/www/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 /var/www/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 /var/www/yii/framework/web/CController.php(291): CFilterChain->run()
#24 /var/www/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 /var/www/yii/framework/web/CWebApplication.php(282): CController->run('')
#26 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user')
#27 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#28 /var/www/workspace_php/pythonfornoobs/index.php(15): CApplication->run()
#29 {main}
REQUEST_URI=/workspace_php/pythonfornoobs/index.php/user
---
2014/04/22 03:09:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('admin')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/workspace_php/pythonfornoobs/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/workspace_php/pythonfornoobs/index.php/admin
---
2014/04/22 13:13:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Não foi possível resolver a requisição "admin".' in /var/www/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('admin')
#1 /var/www/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/workspace_php/pythonfornoobs/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/workspace_php/pythonfornoobs/index.php/admin
---
